### ISSUE TITLE
Which code to use?

### ISSUE THREAD

**Issue by wshager** [lemire/simdcomp#14]
This project references others for compressing sorted arrays, like SIMDCompressionAndIntersection and TurboPFor. AFAICT the core functionality in those projects (i.e. [for.c](https://github.com/lemire/SIMDCompressionAndIntersection/blob/master/src/for.c) ) seems to be identical, whereas the code in this repo is quite different. What are the differences and why are they there?

**Comment by lemire** [comment]
I am not sure how to understand your question.

The README.md provides a description of two related libraries in C++:

https://github.com/lemire/simdcomp#other-libraries

The current library (simdcomp) is in C, a different language.

The TurboPFor library is a C++ library that uses GPL and that was developed entirely indepently, with different codecs.

**Comment by wshager** [comment]
@lemire I've read some of the reference works, and as I understand it 'for' is another scheme that doesn't use SIMD intrinsics.

**Comment by lemire** [comment]
@wshager 

True. FOR is not SIMD-based... normally... but the code present here is different. Sorry, there is no related publication... yet.
