### ISSUE TITLE
Get maxbits for compressed array

### ISSUE THREAD

**Issue by wshager** [lemire/simdcomp#16]
How do I retrieve the maxbits when I only have a compressed array? Is it possible, or do I have to store the value from `maxbits_length`?

**Comment by lemire** [comment]
The library is intentionally low-level. You are responsible for storing the bit width, but we provide examples : 

https://github.com/lemire/simdcomp/blob/master/example.c#L41-L62

**Comment by wshager** [comment]
@lemire understood, thanks.
