### ISSUE TITLE
Could you explain please why using ternary operator instead of bitwise or?

### ISSUE THREAD

**Issue by MBkkt** [lemire/simdcomp#27]
https://github.com/lemire/simdcomp/blob/master/src/avx512bitpacking.c#L10
https://github.com/lemire/simdcomp/blob/master/src/avx512bitpacking.c#L17
https://github.com/lemire/simdcomp/blob/master/src/avxbitpacking.c#L10

**Comment by lemire** [comment]
A bitwise OR could be used and would save one instruction (a single or vs cmp + conditional move). Pull request invited.
