### ISSUE TITLE
how can I compress any size of sorted uint32 array

### ISSUE THREAD

**Issue by hurricane1026** [lemire/simdcomp#35]
from the example.c, the simdpackwithoutmaskd1 can compress a 128 uint32 array. But if my array's length is not the times of 128, I have no idea about the best practise of the simdcomp.
and I want to know the different between simdpackd1 and simdpackwithoutmaskd1.

**Comment by lemire** [comment]
This library is for expert users who wish to design their own compression routines using simdcomp as a building block. We refer you to more accessible libraries in the README file:

https://github.com/lemire/simdcomp?tab=readme-ov-file#other-libraries
